AWSTemplateFormatVersion: "2010-09-09"
Description: ECR
Parameters:
  RepositoryName:
    Type: String
Resources:
  TestEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
