AWSTemplateFormatVersion: "2010-09-09"
Description: Stacks
Parameters:
  ProjectName:
    Type: String
    Default: ecs_sample
  environment:
    Type: String
    Default: production
    Description: production or staging
  MasterUserName:
    Type: String
    Default: rds_admin
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: least 8 characters
Mappings:
  CidrMap:
    production:
      All: 10.0.0.0/16
      PublicA: 10.0.0.0/24
      PublicC: 10.0.1.0/24
      PrivateA: 10.0.100.0/24
      PrivateC: 10.0.101.0/24
    staging:
      All: 10.1.0.0/16
      PublicA: 10.1.0.0/24
      PublicC: 10.1.1.0/24
      PrivateA: 10.1.100.0/24
      PrivateC: 10.1.101.0/24
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        environment: !Ref environment
        VPCIP:
          Fn::FindInMap:
            - CidrMap
            - Ref: environment
            - All
        PublicAIP:
          Fn::FindInMap:
            - CidrMap
            - Ref: environment
            - PublicA
        PublicCIP:
          Fn::FindInMap:
            - CidrMap
            - Ref: environment
            - PublicC
        PrivateAIP:
          Fn::FindInMap:
            - CidrMap
            - Ref: environment
            - PrivateA
        PrivateCIP:
          Fn::FindInMap:
            - CidrMap
            - Ref: environment
            - PrivateC
      TemplateURL: https://s3-ap-northeast-1.amazonaws.com/cf-templates-1q4n5naoe0i3o-ap-northeast-1/sample/vpc.yml
  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ClusterName: SampleCluster
      TemplateURL: https://s3-ap-northeast-1.amazonaws.com/cf-templates-1q4n5naoe0i3o-ap-northeast-1/sample/ecs.yml
  ECRStackNginx:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        RepositoryName: sample_app_nginx
      TemplateURL: https://s3-ap-northeast-1.amazonaws.com/cf-templates-1q4n5naoe0i3o-ap-northeast-1/sample/ecr.yml
  ECRStackPhp:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        RepositoryName: sample_app_php
      TemplateURL: https://s3-ap-northeast-1.amazonaws.com/cf-templates-1q4n5naoe0i3o-ap-northeast-1/sample/ecr.yml
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName: !Ref ProjectName
        environment: !Ref environment
        MasterUserName: !Ref MasterUserName
        MasterUserPassword: !Ref MasterUserPassword
        PrivateASubnetId:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateASubnetId
        PrivateCSubnetId:
          Fn::GetAtt:
            - VPCStack
            - Outputs.PrivateCSubnetId
        RDSFamily: MySQL8.0
        RDSEngine: MySQL
        RDSEngineVersion: 8.0.16
        RDSLicenseModel: general-public-license
        RDSClass: db.t2.micro
        RDSName: sample
        MultiAZchoice: false
        VPCSecurityGroup:
          Fn::GetAtt:
            - VPCStack
            - Outputs.EcsSecurityGroup
      TemplateURL: https://s3-ap-northeast-1.amazonaws.com/cf-templates-1q4n5naoe0i3o-ap-northeast-1/sample/rds.yml
Outputs:
  VPCId:
    Value:
      Fn::GetAtt:
        - VPCStack
        - Outputs.VPCId
  PublicASubnetId:
    Value:
      Fn::GetAtt:
        - VPCStack
        - Outputs.PublicASubnetId
  PublicCSubnetId:
    Value:
      Fn::GetAtt:
        - VPCStack
        - Outputs.PublicCSubnetId
  PrivateASubnetId:
    Value:
      Fn::GetAtt:
        - VPCStack
        - Outputs.PrivateASubnetId
  PrivateCSubnetId:
    Value:
      Fn::GetAtt:
        - VPCStack
        - Outputs.PrivateCSubnetId
  EcsSecurityGroup:
    Value:
      Fn::GetAtt:
        - VPCStack
        - Outputs.EcsSecurityGroup
  ClusterId:
    Value:
      Fn::GetAtt:
        - ECSStack
        - Outputs.ClusterId
